server:
    port: 8888
encrypt:
    key: ABCDEFGHIJKLMNOPQRSTUVWXYZ
spring:
    security:
        user:
            name: obinna
            password: obinna
    cloud:
        config:
            server:
                encrypt:
                    enabled: false
                git:
                    uri: https://github.com/obinnaogbonnajoseph/spring-cloudconfig
                    search-paths:
                    - station*
                    repos:
                        perf:
                            pattern: '*/perf'
                            uri: https://github.com/obinnaogbonnajoseph/spring-cloudconfig-perf
                            search-paths:
                            - station*
